### ISSUE TITLE
lcsniff crashes when clicking on empty row after USB capture

### ISSUE THREAD

**Issue by jeanthom** [lambdaconcept/usb2sniffer-qt#7]
Here's GDB's backtrace :

```
#0  0x00000000004159b6 in USBItem::asciiPacket() (this=0x0)
    at ../usbitem.cpp:95
#1  0x000000000040e0cc in MainWindow::updateAscii(QModelIndex const&)
    (this=0x7fffffffd530, index=...) at ../mainwindow.cpp:304
#2  0x0000000000415325 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<QModelIndex const&>, void, void (MainWindow::*)(QModelIndex const&)>::call(void (MainWindow::*)(QModelIndex const&), MainWindow*, void**) (f=
    (void (MainWindow::*)(MainWindow * const, const QModelIndex &)) 0x40e046 <MainWindow::updateAscii(QModelIndex const&)>, o=0x7fffffffd530, arg=0x7fffffffc660) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:134
#3  0x000000000041514f in QtPrivate::FunctionPointer<void (MainWindow::*)(QModelIndex const&)>::call<QtPrivate::List<QModelIndex const&>, void>(void (MainWindow::*)(QModelIndex const&), MainWindow*, void**) (f=
    (void (MainWindow::*)(MainWindow * const, const QModelIndex &)) 0x40e046 <MainWindow::updateAscii(QModelIndex const&)>, o=0x7fffffffd530, arg=0x7fffffffc660) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:167
#4  0x0000000000414c6d in QtPrivate::QSlotObject<void (MainWindow::*)(QModelIndex const&), QtPrivate::List<QModelIndex const&>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)
    (which=1, this_=0x913790, r=0x7fffffffd530, a=0x7fffffffc660, ret=0x0)
    at /usr/include/qt5/QtCore/qobjectdefs_impl.h:396
#5  0x00007ffff71de1c3 in QMetaObject::activate(QObject*, int, int, void**) ()
    at /lib64/libQt5Core.so.5
#6  0x00007ffff7cf3d49 in QAbstractItemView::clicked(QModelIndex const&) ()
    at /lib64/libQt5Widgets.so.5
#7  0x00007ffff7cf74f6 in QAbstractItemView::mouseReleaseEvent(QMouseEvent*) ()
    at /lib64/libQt5Widgets.so.5
#8  0x00007ffff7d6a813 in QTreeView::mouseReleaseEvent(QMouseEvent*) ()
    at /lib64/libQt5Widgets.so.5
#9  0x00007ffff7ae4378 in QWidget::event(QEvent*) ()
    at /lib64/libQt5Widgets.so.5
#10 0x00007ffff7b88ac2 in QFrame::event(QEvent*) ()
    at /lib64/libQt5Widgets.so.5
#11 0x00007ffff7d0091b in QAbstractItemView::viewportEvent(QEvent*) ()
    at /lib64/libQt5Widgets.so.5
#12 0x00007ffff7d6a07f in QTreeView::viewportEvent(QEvent*) ()
    at /lib64/libQt5Widgets.so.5
#13 0x00007ffff71b5d0e in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#14 0x00007ffff7aa5275 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () at /lib64/libQt5Widgets.so.5
#15 0x00007ffff7aacbe8 in QApplication::notify(QObject*, QEvent*) ()
    at /lib64/libQt5Widgets.so.5
#16 0x00007ffff71b5ec6 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () at /lib64/libQt5Core.so.5
#17 0x00007ffff7aabedd in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
    at /lib64/libQt5Widgets.so.5
#18 0x00007ffff7aff118 in  () at /lib64/libQt5Widgets.so.5
#19 0x00007ffff7b01cbe in  () at /lib64/libQt5Widgets.so.5
#20 0x00007ffff7aa5285 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () at /lib64/libQt5Widgets.so.5
#21 0x00007ffff7aac9a0 in QApplication::notify(QObject*, QEvent*) ()
    at /lib64/libQt5Widgets.so.5
#22 0x00007ffff71b5ec6 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () at /lib64/libQt5Core.so.5
#23 0x00007ffff75564d3 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib64/libQt5Gui.so.5
#24 0x00007ffff75585d5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /lib64/libQt5Gui.so.5
#25 0x00007ffff753370b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Gui.so.5
#26 0x00007fffe70b985f in  () at /lib64/libQt5XcbQpa.so.5
#27 0x00007ffff71b4e0b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#28 0x00007ffff71bced6 in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#29 0x000000000040c0c6 in main(int, char**) (argc=1, argv=0x7fffffffd6b8)
    at ../main.cpp:10
```

**Comment by jeanthom** [comment]
Fixed by #11
